### ISSUE TITLE
Grafana & Prometheus

### ISSUE THREAD

**Issue by Koziar** [semester-groupies/hacker-news-backend#2]
Dudes, I think you might have an issue with Prometheus or Grafana. I mean Grafana is up and running, however it's having a tough time to display your data from Prometheus. I have tried to reach your Prometheus and see if it's up but [in your SLA file](https://docs.google.com/document/d/1Mnaoi8SugXObp7oG-VGjqv6HT7qWtPxZvYnywFaI5To/edit) I couldn't find the address to it, I have tried the same machine as Grafana with a default port 9090 but the site couldn't be reached.
On Grafana I see this: 
![screen shot 2017-11-13 at 16 57 37](https://user-images.githubusercontent.com/9032472/32735201-6c04d622-c894-11e7-98ed-e9e59a926781.png)

**Comment by Koziar** [comment]
We actually just checked  the Prometheus state on Grafana, looks like it's down ![screen shot 2017-11-13 at 17 03 57](https://user-images.githubusercontent.com/9032472/32735309-a9e0c03c-c894-11e7-95c7-6ef7de768a75.png)

**Comment by Koziar** [comment]
`http://www.favl.dk:8080/metrics` looks fine, so you probably just have to restart the Pormetheus container

**Comment by fandul** [comment]
Restarted, both containers, Prometheus went down.

**Comment by Koziar** [comment]
I confirm, it's back up again. Why did it go down tho? Have you investigated that issue?
