### ISSUE TITLE
Prometheus down

### ISSUE THREAD

**Issue by Koziar** [semester-groupies/hacker-news-backend#6]
I have discovered that at 16:30 Grafana lost all data, I suspect it's prometheus again.

**Comment by Koziar** [comment]
![nov-18-2017 16-40-24](https://user-images.githubusercontent.com/9032472/32982097-3cee9352-cc7f-11e7-80c6-96b369b4ce99.gif)

**Comment by fandul** [comment]
fixed, prometheus went down. restarted the service.
